[auth.ldap]
    name        = ""
    host        = ""
    port        = ""
    useTLS      = false
    email       = ""
    userBase    = ""
    userFilter  = ""
    userDN      = ""
[influxdb]
    addr        = "127.0.0.1:8086"
    username    = ""
    password    = ""
    userAgent   = ""
[web]
    addr        = "127.0.0.1:8888"
[blacklist]
    queries     = [""]
