[auth]
    [token]
        pubKeyPath  = ""        # public key file path
        privKeyPath = ""        # private key file path
        method      = ""        # method of signing, e.g: RS256, HS256
        ttl         = 10        # lifetime of the token in minutes. Token is not valid is expired
    [ldap]
        name        = ""        # a name assigned to the new method of authorization
        host        = ""        # example: mydomain.com
        port        = ""        # example: 636
        useTLS      = false     # whether to use TLS when connecting to the LDAP server
        bindDN      = ""        # example: cn=Search,dc=mydomain,dc=com
        bindPasswd  = ""        # the password for the Bind DN
        userBase    = ""        # example: ou=Users,dc=mydomain,dc=com
        userFilter  = ""        # example: (&(objectClass=*)(uid=%s)), '%s' will be substituted with user's username
        userDN      = ""        # example: cn=%s,ou=Users,dc=mydomain,dc=com
        useBindDN   = false     # use bindDN auth instead of simple auth
        attrUsername= ""
        attrName    = ""
        attrSurname = ""
        attrMail    = ""        # attribute of user's record containing email, example: 'mail'

[influxdb]
    addr        = "127.0.0.1:8086"
    username    = ""
    password    = ""
    userAgent   = ""
[web]
    addr        = "127.0.0.1:8888"
[blacklist]
    queries     = [""]        # blacklist of queries that is prohibitied to run, example: "SHOW DATABASES"
    adminGroup  = "admin"     # admin group name, this group members can see & run everything
# group specifications, group members have allowed and denied query list
[[groups]]                # [[groups]]
    ou = ""               #     ou = "Global group"
    cn = ""               #     cn = "Admin"
    deniedQueries = [     #     deniedQueries = [
        "",               #         "Show measurements",
        ""                #         "SHOW TAGS"
    ]                     #     ]
